### ISSUE TITLE
JFX 회원정보 + ERP + 모듈화

### ISSUE THREAD

**Issue by habanera03** [habanera03/buengbueng#19]
시작할게여.
src - fx.login.bean : Fx 회원관리 BEAN
views - fxUserInfo : Fx 회원관리 jsp

**Comment by sleepygloa** [comment]
잘부탁드립니다..

**Comment by habanera03** [comment]
WebContent 안에 FX_src 폴더에 javafx 폴더 및 파일들 넣어놨습니다.

1. 로그인 시 useTimeL 테이블에 사용 로그 남김 (id, loginTime, ip)
2. 사용자 잔액 가지고 사용 가능 시간 계산 후 카운트
3. 로그아웃 시 useTimeL 테이블에 사용 종료 시간 정보 추가 (logoutTime)
4. 아이디 / 비밀번호 찾기 1차 완료

**Comment by habanera03** [comment]
WebContent 안에 JFX(사용자 프로그램), JFXBoss(사장님 프로그램) 있습니다.
  
  사장님
  1. 모듈화 : 추가, 수정, 삭제, 모듈 변경 가능
  
  사용자
  1. 대여 : 해당 가맹점에서 대여하는 품목 확인 가능
                  대여 물품 주문 가능

추후 일정
  1.  사용자 물품 대여
  2. 모듈화 : 메뉴 위치 이동
  3. 사용자 메뉴 주문
