### ISSUE TITLE
ERP :정산 - 일일정산

### ISSUE THREAD

**Issue by sleepygloa** [habanera03/buengbueng#24]
일정한 시간에 이루어지는 정보를 DB로 쏜다.

**Comment by sleepygloa** [comment]
명훈이에게 할당

**Comment by LeeMyounghun** [comment]
타이머 버튼을 고려했으나 하루 끝나는 시점에 하면 절대적으로 다음날과 오늘 할 수 없기에 
현재일 기준으로  "어제 00시 00분 00초" 부터 "어제 23시 59분 59초"로 매일 설정을 하여 
정산을 24시가 넘어가는 기준으로 하여 어제 있던 모든 데이터를 조회한 후 정산을 요청한다.
정산 요청이 끝나면 내역에서 현황을 볼 수 있으며 관리자가 승인허가가 승락 된 후 부터 정상적인
정산요청이 완료된다.
