### ISSUE TITLE
유효성 검사 Extends VS Autowired

### ISSUE THREAD

**Issue by sleepygloa** [habanera03/buengbueng#8]
유효성 검사를 추가하려고하는데
상속을 받아서 필요한곳에 객체생성을 하는 방법이 좋을까?

**Comment by wodnrdl** [comment]
extend or Autowired

**Comment by sleepygloa** [comment]
# Autowired 방식으로 구현함.
상속을 받을 수 도 있지만, Spring 방식으로 진행하는게 프로젝트 취지와 맞다고 생각
